name: API Test & Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Run only on the main branch
  pull_request:
    branches:
      - main  # Run tests on PRs to main

jobs:
  test-api:
    name: Test API Endpoints
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DATABASE_URL: ${{ secrets.MYSQL_DATABASE_URL }}  # Use in tests
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Install Test Dependencies
        run: |
          pip install -r dev-requirements.txt
          
      - name: Run API Tests
        run: |
          pytest tests/  # Run API test cases

  deploy:
    name: Build & Deploy to Cloud Run
    if: github.ref == 'refs/heads/main'  # Runs only on main branch
    needs: test-api  # Only run if tests pass
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.MYSQL_DATABASE_URL }}  # Use in deployment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/decoding-the-roads/decoding-the-roads:${{ github.sha }} .

      - name: Push Docker Image to GCR
        run: |
          docker push gcr.io/decoding-the-roads/decoding-the-roads:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy decoding-the-roads \
            --image gcr.io/decoding-the-roads/decoding-the-roads:${{ github.sha }} \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated \
            --set-env-vars DATABASE_URL=${{ secrets.MYSQL_DATABASE_URL }}

  cleanup-old-images:
    name: Delete Old Docker Images
    needs: deploy  # Only run after deployment
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Delete Old Docker Images
        run: |
          # Keep the latest 3 images and delete older ones
          gcloud container images list-tags gcr.io/decoding-the-roads/decoding-the-roads \
            --sort-by=~TIMESTAMP --limit=3 --format="get(digest)" | while read digest; do
              gcloud container images delete gcr.io/decoding-the-roads/decoding-the-roads@$digest --force-delete-tags --quiet
            done
